version: 2
registries:
  npm-registry-npm-pkg-github-com:
    type: npm-registry
    url: https://npm.pkg.github.com
    token: "${{secrets.NPM_REGISTRY_NPM_PKG_GITHUB_COM_TOKEN}}"

updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 15.0.0
  - dependency-name: react
    versions:
    - 17.0.1
    - 17.0.2
  - dependency-name: react-dom
    versions:
    - 17.0.1
    - 17.0.2
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.16.0
    - 4.21.0
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 4.15.0
    - 4.15.2
  - dependency-name: eslint-config-prettier
    versions:
    - 8.0.0
  - dependency-name: "@babel/core"
    versions:
    - 7.13.0
  registries:
  - npm-registry-npm-pkg-github-com
