version: 2
registries:
  npm-github:
    type: npm-registry
    url: https://npm.pkg.github.com
    token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
  docker-github:
    type: docker-registry
    url: https://ghcr.io
    username: USERNAME
    password: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10

  - package-ecosystem: "npm"
    directory: "/"
    registries: "*"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10

  - package-ecosystem: "docker"
    registries: "*"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
