name: Test
on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "**"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-node-

      - uses: actions/setup-node@v2

      - name: Install
        run: yarn install

      - name: Test Types
        run: yarn test:types

      - name: Test Lint
        run: yarn test:lint

      - name: Build
        run: yarn build

      - name: Build Docz
        run: yarn docz:build
